package pojo;
// Generated Dec 11, 2017 12:43:49 AM by Hibernate Tools 4.3.1



/**
 * Ctphieuxuat generated by hbm2java
 */
public class Ctphieuxuat  implements java.io.Serializable {


     private Integer ctpxId;
     private Phieuxuat phieuxuat;
     private Sanpham sanpham;
     private Trangthai trangthai;
     private Integer soluong;
     private Integer giaxuat;

    public Ctphieuxuat() {
    }

    public Ctphieuxuat(Phieuxuat phieuxuat, Sanpham sanpham, Trangthai trangthai, Integer soluong, Integer giaxuat) {
       this.phieuxuat = phieuxuat;
       this.sanpham = sanpham;
       this.trangthai = trangthai;
       this.soluong = soluong;
       this.giaxuat = giaxuat;
    }
   
    public Integer getCtpxId() {
        return this.ctpxId;
    }
    
    public void setCtpxId(Integer ctpxId) {
        this.ctpxId = ctpxId;
    }
    public Phieuxuat getPhieuxuat() {
        return this.phieuxuat;
    }
    
    public void setPhieuxuat(Phieuxuat phieuxuat) {
        this.phieuxuat = phieuxuat;
    }
    public Sanpham getSanpham() {
        return this.sanpham;
    }
    
    public void setSanpham(Sanpham sanpham) {
        this.sanpham = sanpham;
    }
    public Trangthai getTrangthai() {
        return this.trangthai;
    }
    
    public void setTrangthai(Trangthai trangthai) {
        this.trangthai = trangthai;
    }
    public Integer getSoluong() {
        return this.soluong;
    }
    
    public void setSoluong(Integer soluong) {
        this.soluong = soluong;
    }
    public Integer getGiaxuat() {
        return this.giaxuat;
    }
    
    public void setGiaxuat(Integer giaxuat) {
        this.giaxuat = giaxuat;
    }




}


