package pojo;
// Generated Dec 11, 2017 12:43:49 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Danhmuc generated by hbm2java
 */
public class Danhmuc  implements java.io.Serializable {


     private Integer dmId;
     private Integer dmChaid;
     private String tendanhmuc;
     private String mota;
     private Set sanphams = new HashSet(0);

    public Danhmuc() {
    }

    public Danhmuc(Integer dmChaid, String tendanhmuc, String mota, Set sanphams) {
       this.dmChaid = dmChaid;
       this.tendanhmuc = tendanhmuc;
       this.mota = mota;
       this.sanphams = sanphams;
    }
   
    public Integer getDmId() {
        return this.dmId;
    }
    
    public void setDmId(Integer dmId) {
        this.dmId = dmId;
    }
    public Integer getDmChaid() {
        return this.dmChaid;
    }
    
    public void setDmChaid(Integer dmChaid) {
        this.dmChaid = dmChaid;
    }
    public String getTendanhmuc() {
        return this.tendanhmuc;
    }
    
    public void setTendanhmuc(String tendanhmuc) {
        this.tendanhmuc = tendanhmuc;
    }
    public String getMota() {
        return this.mota;
    }
    
    public void setMota(String mota) {
        this.mota = mota;
    }
    public Set getSanphams() {
        return this.sanphams;
    }
    
    public void setSanphams(Set sanphams) {
        this.sanphams = sanphams;
    }




}


