package pojo;
// Generated Dec 11, 2017 12:05:45 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Phieuxuat generated by hbm2java
 */
public class Phieuxuat  implements java.io.Serializable {


     private Integer pxId;
     private Taikhoan taikhoan;
     private Trangthai trangthai;
     private Date ngayxuat;
     private Integer tongtien;
     private String phieuxuatcol;
     private Set ctphieuxuats = new HashSet(0);

    public Phieuxuat() {
    }

    public Phieuxuat(Taikhoan taikhoan, Trangthai trangthai, Date ngayxuat, Integer tongtien, String phieuxuatcol, Set ctphieuxuats) {
       this.taikhoan = taikhoan;
       this.trangthai = trangthai;
       this.ngayxuat = ngayxuat;
       this.tongtien = tongtien;
       this.phieuxuatcol = phieuxuatcol;
       this.ctphieuxuats = ctphieuxuats;
    }
   
    public Integer getPxId() {
        return this.pxId;
    }
    
    public void setPxId(Integer pxId) {
        this.pxId = pxId;
    }
    public Taikhoan getTaikhoan() {
        return this.taikhoan;
    }
    
    public void setTaikhoan(Taikhoan taikhoan) {
        this.taikhoan = taikhoan;
    }
    public Trangthai getTrangthai() {
        return this.trangthai;
    }
    
    public void setTrangthai(Trangthai trangthai) {
        this.trangthai = trangthai;
    }
    public Date getNgayxuat() {
        return this.ngayxuat;
    }
    
    public void setNgayxuat(Date ngayxuat) {
        this.ngayxuat = ngayxuat;
    }
    public Integer getTongtien() {
        return this.tongtien;
    }
    
    public void setTongtien(Integer tongtien) {
        this.tongtien = tongtien;
    }
    public String getPhieuxuatcol() {
        return this.phieuxuatcol;
    }
    
    public void setPhieuxuatcol(String phieuxuatcol) {
        this.phieuxuatcol = phieuxuatcol;
    }
    public Set getCtphieuxuats() {
        return this.ctphieuxuats;
    }
    
    public void setCtphieuxuats(Set ctphieuxuats) {
        this.ctphieuxuats = ctphieuxuats;
    }




}


