package pojo;
// Generated Dec 11, 2017 12:43:49 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Trangthai generated by hbm2java
 */
public class Trangthai  implements java.io.Serializable {


     private Integer ttId;
     private Integer ttChaid;
     private String tentrangthai;
     private Set ctphieuxuats = new HashSet(0);
     private Set sanphams = new HashSet(0);
     private Set phieuxuats = new HashSet(0);
     private Set ctphieunhaps = new HashSet(0);
     private Set phieunhaps = new HashSet(0);
     private Set taikhoans = new HashSet(0);

    public Trangthai() {
    }

    public Trangthai(Integer ttChaid, String tentrangthai, Set ctphieuxuats, Set sanphams, Set phieuxuats, Set ctphieunhaps, Set phieunhaps, Set taikhoans) {
       this.ttChaid = ttChaid;
       this.tentrangthai = tentrangthai;
       this.ctphieuxuats = ctphieuxuats;
       this.sanphams = sanphams;
       this.phieuxuats = phieuxuats;
       this.ctphieunhaps = ctphieunhaps;
       this.phieunhaps = phieunhaps;
       this.taikhoans = taikhoans;
    }
   
    public Integer getTtId() {
        return this.ttId;
    }
    
    public void setTtId(Integer ttId) {
        this.ttId = ttId;
    }
    public Integer getTtChaid() {
        return this.ttChaid;
    }
    
    public void setTtChaid(Integer ttChaid) {
        this.ttChaid = ttChaid;
    }
    public String getTentrangthai() {
        return this.tentrangthai;
    }
    
    public void setTentrangthai(String tentrangthai) {
        this.tentrangthai = tentrangthai;
    }
    public Set getCtphieuxuats() {
        return this.ctphieuxuats;
    }
    
    public void setCtphieuxuats(Set ctphieuxuats) {
        this.ctphieuxuats = ctphieuxuats;
    }
    public Set getSanphams() {
        return this.sanphams;
    }
    
    public void setSanphams(Set sanphams) {
        this.sanphams = sanphams;
    }
    public Set getPhieuxuats() {
        return this.phieuxuats;
    }
    
    public void setPhieuxuats(Set phieuxuats) {
        this.phieuxuats = phieuxuats;
    }
    public Set getCtphieunhaps() {
        return this.ctphieunhaps;
    }
    
    public void setCtphieunhaps(Set ctphieunhaps) {
        this.ctphieunhaps = ctphieunhaps;
    }
    public Set getPhieunhaps() {
        return this.phieunhaps;
    }
    
    public void setPhieunhaps(Set phieunhaps) {
        this.phieunhaps = phieunhaps;
    }
    public Set getTaikhoans() {
        return this.taikhoans;
    }
    
    public void setTaikhoans(Set taikhoans) {
        this.taikhoans = taikhoans;
    }




}


